service: auth

# Add the serverless-webpack plugin
plugins:
  - serverless-hooks-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-s3-sync

provider:
  name: aws

  region: us-east-1
  runtime: nodejs8.10
  memorySize: 256
  timeout: 6

  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    TABLE_NAME: ${self:custom.tableName}

    SSM_PRIVATE_KEY_NAME: auth-jwt-${self:provider.stage}-private.pem
    SSM_PUBLIC_KEY_NAME: auth-jwt-${self:provider.stage}-public.pem

    MAILGUN_API_KEY: "asdf"
    MAILGUN_DOMAIN: "mg.jman.me"

custom:
  hooks:
    before:package:createDeploymentArtifacts:
      - "yarn --cwd interface/ build"

  s3Sync:
    - bucketName: ${self:custom.interfaceBucketName}
      localDir: interface/build
      acl: public-read

  interfaceBucketNames:
    prod: auth.jman.me
    default: ${self:provider.stage}.auth.jman.me
  interfaceBucketName: ${self:custom.interfaceBucketNames.${self:provider.stage}, self:custom.interfaceBucketNames.default}

  tableName: auth-${self:provider.stage}
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:provider.stage}, self:custom.tableThroughputs.default}

  deletionPolicys:
    prod: "Retain"
    default: "Delete"
  deletionPolicy: ${self:custom.deletionPolicys.${self:provider.stage}, self:custom.deletionPolicys.default}

package:
  individually: true
  include:
    - "!**"
    - "src/**"
    - "!src/endpoints/**"

functions:
  - ${file(./src/endpoints/create/definition.yml)}
  - ${file(./src/endpoints/login/definition.yml)}

resources:
  - ${file(./resources/auth-table.yml)}
  - ${file(./resources/interface-bucket.yml)}
